### ISSUE TITLE
D3D9 support?

### ISSUE THREAD

**Issue by donizettilorenzo** [CookiePLMonster/DXHRDC-GFX#10]
Now it's missing. Any plan to add the support for D3D9 rendering path? (It's the only way to get MSAA working on NVidia GPUs or through dgVoodoo2 for every GPU).

**Comment by donizettilorenzo** [comment]
Up!

**Comment by CookiePLMonster** [comment]
No, it's not planned. You should be able to use other means of anti-aliasing together with the mod.

**Comment by 3371-Alpha** [comment]
That's too bad. Most post processing AA methods are fairly poor compared to their traditional counterparts; in fact it's the only feature the D3D11 renderer is lacking in. Understandably though, writing for two renderers would be a pain.

**Comment by CookiePLMonster** [comment]
You might potentially have some luck with third party solutions to inject AA, but if that doesn't help then I don't think I have other ideas.
