### ISSUE TITLE
Depth of Fields breaks with DXHR bloom

### ISSUE THREAD

**Issue by CookiePLMonster** [CookiePLMonster/DXHRDC-GFX#7]
Pasting from the article comments for easier tracking:

https://cookieplmonster.github.io/2020/04/26/dxhr-dc-gold-filter/#comment-4892867823

**Comment by donizettilorenzo** [comment]
Minor issue, depth of field affects only the dialogues.

Ah, how we can build this plugin by ourselves from the source? Appveyor?

**Comment by CookiePLMonster** [comment]
> Minor issue, depth of field affects only the dialogues.

Seems not to happen on nvidia too, as far as I can tell.



> Ah, how we can build this plugin by ourselves from the source? Appveyor?

I don't have builds set up so you'd need to:
1. Generate the project with [premake](https://premake.github.io/download.html).
2. Build it using Visual Studio (only tested with 2019, VS2017 may or may not work).

**Comment by donizettilorenzo** [comment]
Thanks, perfectly working :)

**Comment by CookiePLMonster** [comment]
> Thanks, perfectly working :)

You are not referring to the DoF bug though, are you? I haven't done anything regarding it yet so I don't expect it to be magically fixed.

**Comment by donizettilorenzo** [comment]
No, the toolchain/build process :D
