### ISSUE TITLE
In-game Cutscenes freezing

### ISSUE THREAD

**Issue by Mobeeuz** [CookiePLMonster/DXHRDC-GFX#9]
In the GOG release, the cutscenes will just freeze, but audio will continue.

**Comment by CookiePLMonster** [comment]
I quickly checked and could not reproduce.
1. What are your exact graphics settings?
2. Do you have subtitles enabled?
3. What "in-game cutscenes" do you mean exactly? Provide a screenshot if possible.

**Comment by Mobeeuz** [comment]
I have everything set to max, including soft shadows, 1080p. In-game, like conversations with choices, not movies - actual gameplay is fine. Tried DX9, but your mod doesn't appear to work in DX9. Once you leave to go to the chopper, the first conversation with the pilot, the scene just freezes. Picks up again, and then freezes.

**Comment by Mobeeuz** [comment]
Okay I've pinpointed it, it's depth of field on max. If I set it to normal, the problem goes away.

**Comment by CookiePLMonster** [comment]
Build 2 fixed issues with DoF set to High and so I never had this happen. It must be something else conflicting, but I can't pinpoint it yet.

**Comment by CookiePLMonster** [comment]
Does it happen with Gold Filter disabled? It should not.

**Comment by Mobeeuz** [comment]
Correct, it does not.

**Comment by CookiePLMonster** [comment]
OK, reproduced it with MLAA + DoF set to High + subtitles **disabled**. For the time being, just enable subtitles and it'll work fine!

I'll look into this soon.

**Comment by reaper666735** [comment]
combat takedowns and ingame cutscenes (not movie) lag out/skip sometimes on the Steam release, could it also be related ?

**Comment by CookiePLMonster** [comment]
> combat takedowns and ingame cutscenes (not movie) lag out/skip sometimes on the Steam release, could it also be related ?

Only if you don't have those issues with the mod installed/gold filter enabled.

**Comment by reaper666735** [comment]
that would be a yes then :p

**Comment by CookiePLMonster** [comment]
> that would be a yes then :p

Do you have subtitles enabled? Are you using any overlays like Rivatuner?

**Comment by reaper666735** [comment]
no overlay just your Mod active, Subtitles are on

**Comment by CookiePLMonster** [comment]
Solved with cdd720e004e1d679a642fc92f1989c571a90032f. Turns out it could have also happened in cutscenes with subtitles enabled, but could potentially freeze the moments where subtitles are not showing - so it might be the issue @reaper666735 encountered.
